-- CreateTable
CREATE TABLE `Invoice` (
    `ID_INVOICE` INTEGER NOT NULL AUTO_INCREMENT,
    `NO_INVOICE` VARCHAR(191) NULL,
    `TGL_PELUNASAN` DATETIME(3) NULL,
    `TAX` DOUBLE NULL,
    `JAMINAN` DOUBLE NULL,
    `DEPOSIT` DOUBLE NULL,
    `SISA_KEKURANGAN` DOUBLE NULL,
    `ID_RESERVASI` INTEGER NULL,

    PRIMARY KEY (`ID_INVOICE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Invoice` ADD CONSTRAINT `Invoice_ID_RESERVASI_fkey` FOREIGN KEY (`ID_RESERVASI`) REFERENCES `Reservasi`(`ID_RESERVASI`) ON DELETE SET NULL ON UPDATE CASCADE;
