-- CreateTable
CREATE TABLE `Role` (
    `ID_ROLE` INTEGER NOT NULL AUTO_INCREMENT,
    `NAMA_ROLE` VARCHAR(191) NULL,

    PRIMARY KEY (`ID_ROLE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Akun` (
    `ID_AKUN` INTEGER NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(191) NULL,
    `PASSWORD` VARCHAR(191) NULL,
    `ID_ROLE` INTEGER NULL,

    PRIMARY KEY (`ID_AKUN`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Customer` (
    `ID_CUSTOMER` INTEGER NOT NULL AUTO_INCREMENT,
    `JENIS_CUSTOMER` VARCHAR(191) NULL,
    `NAMA_CUSTOMER` VARCHAR(191) NULL,
    `NAMA_INSTITUSI` VARCHAR(191) NULL,
    `NO_TELP` VARCHAR(191) NULL,
    `EMAIL` VARCHAR(191) NULL,
    `ALAMAT` VARCHAR(191) NULL,
    `ID_AKUN` INTEGER NULL,

    PRIMARY KEY (`ID_CUSTOMER`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Pegawai` (
    `ID_PEGAWAI` INTEGER NOT NULL AUTO_INCREMENT,
    `NAMA_PEGAWAI` VARCHAR(191) NULL,
    `ID_AKUN` INTEGER NULL,

    PRIMARY KEY (`ID_PEGAWAI`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Akun` ADD CONSTRAINT `Akun_ID_ROLE_fkey` FOREIGN KEY (`ID_ROLE`) REFERENCES `Role`(`ID_ROLE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Customer` ADD CONSTRAINT `Customer_ID_AKUN_fkey` FOREIGN KEY (`ID_AKUN`) REFERENCES `Akun`(`ID_AKUN`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Pegawai` ADD CONSTRAINT `Pegawai_ID_AKUN_fkey` FOREIGN KEY (`ID_AKUN`) REFERENCES `Akun`(`ID_AKUN`) ON DELETE SET NULL ON UPDATE CASCADE;
