GET http://localhost:3000/api/kamar/getAllKamar

### 

POST http://localhost:3000/api/kamar/addKamar
Content-Type: application/json

{
  "NO_KAMAR": 105,
  "JENIS_KAMAR": "VIP",
  "JENIS_BED": "DOUBLE",
  "KAPASITAS": 2,
  "LUAS_KAMAR": 20,
  "FASILITAS": "AC, TV, KULKAS, WIFI"
}

###

PUT http://localhost:3000/api/kamar/updateKamar/5
Content-Type: application/json

{
  "NO_KAMAR": 105,
  "JENIS_KAMAR": "YOILAHH",
  "JENIS_BED": "CINCAI",
  "KAPASITAS": 2,
  "LUAS_KAMAR": 20,
  "FASILITAS": "AC, TV, KULKAS, WIFI, SEMUANYA BROK"
}


###

DELETE http://localhost:3000/api/kamar/deleteKamar/1