-- CreateTable
CREATE TABLE `Detail_Reservasi_Kamar` (
    `ID_DETAIL_RESERVASI_KAMAR` INTEGER NOT NULL AUTO_INCREMENT,
    `JUMLAH` INTEGER NULL,
    `TOTAL_HARGA_KAMAR` DOUBLE NULL,
    `ID_TARIF` INTEGER NULL,
    `ID_RESERVASI` INTEGER NULL,

    PRIMARY KEY (`ID_DETAIL_RESERVASI_KAMAR`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Detail_Reservasi_Fasilitas` (
    `ID_DETAIL_RESERVASI_FASILITAS` INTEGER NOT NULL AUTO_INCREMENT,
    `JUMLAH` INTEGER NULL,
    `TOTAL_HARGA_FASILITAS` DOUBLE NULL,
    `ID_FASILITAS` INTEGER NULL,
    `ID_RESERVASI` INTEGER NULL,

    PRIMARY KEY (`ID_DETAIL_RESERVASI_FASILITAS`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Reservasi` (
    `ID_RESERVASI` INTEGER NOT NULL AUTO_INCREMENT,
    `TGL_RESERVASI` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `TGL_CHECKIN` DATETIME(3) NULL,
    `TGL_CHECKOUT` DATETIME(3) NULL,
    `JML_DEWASA` INTEGER NULL,
    `JML_ANAK` INTEGER NULL,
    `TOTAL_BAYAR` DOUBLE NULL,
    `STATUS` INTEGER NULL,
    `ID_PEGAWAI` INTEGER NULL,
    `ID_CUSTOMER` INTEGER NULL,

    PRIMARY KEY (`ID_RESERVASI`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Detail_Reservasi_Kamar` ADD CONSTRAINT `Detail_Reservasi_Kamar_ID_RESERVASI_fkey` FOREIGN KEY (`ID_RESERVASI`) REFERENCES `Reservasi`(`ID_RESERVASI`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Detail_Reservasi_Kamar` ADD CONSTRAINT `Detail_Reservasi_Kamar_ID_TARIF_fkey` FOREIGN KEY (`ID_TARIF`) REFERENCES `Tarif`(`ID_TARIF`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Detail_Reservasi_Fasilitas` ADD CONSTRAINT `Detail_Reservasi_Fasilitas_ID_RESERVASI_fkey` FOREIGN KEY (`ID_RESERVASI`) REFERENCES `Reservasi`(`ID_RESERVASI`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Detail_Reservasi_Fasilitas` ADD CONSTRAINT `Detail_Reservasi_Fasilitas_ID_FASILITAS_fkey` FOREIGN KEY (`ID_FASILITAS`) REFERENCES `Fasilitas_Tambahan`(`ID_FASILITAS`) ON DELETE SET NULL ON UPDATE CASCADE;
