-- AlterTable
ALTER TABLE `reservasi` ADD COLUMN `CREATED_AT_MONTH` VARCHAR(191) NULL,
    ADD COLUMN `CREATED_AT_YEAR` VARCHAR(191) NULL,
    ADD COLUMN `JENIS_CUSTOMER` VARCHAR(191) NULL,
    ALTER COLUMN `TGL_RESERVASI` DROP DEFAULT;
