-- CreateTable
CREATE TABLE `Fasilitas_Tambahan` (
    `ID_FASILITAS` INTEGER NOT NULL AUTO_INCREMENT,
    `NAMA_FASILITAS` VARCHAR(191) NULL,
    `SATUAN` VARCHAR(191) NULL,
    `HARGA` DOUBLE NULL,

    PRIMARY KEY (`ID_FASILITAS`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
