-- AddForeignKey
ALTER TABLE `Reservasi` ADD CONSTRAINT `Reservasi_ID_PEGAWAI_fkey` FOREIGN KEY (`ID_PEGAWAI`) REFERENCES `Pegawai`(`ID_PEGAWAI`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Reservasi` ADD CONSTRAINT `Reservasi_ID_CUSTOMER_fkey` FOREIGN KEY (`ID_CUSTOMER`) REFERENCES `Customer`(`ID_CUSTOMER`) ON DELETE SET NULL ON UPDATE CASCADE;
