-- CreateTable
CREATE TABLE `Season` (
    `ID_SEASON` INTEGER NOT NULL AUTO_INCREMENT,
    `JENIS_SEASON` VARCHAR(191) NULL,
    `TGL_MULAI` DATETIME(3) NULL,
    `TGL_AKHIR` DATETIME(3) NULL,
    `HARGA` DOUBLE NULL,

    PRIMARY KEY (`ID_SEASON`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
